CREATE TABLE policy_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    document TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE active_policy (
    id INTEGER PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES policy_revision(id),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE audit_event (
    id VARCHAR(100) PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    kind VARCHAR(30) NOT NULL,
    request_id VARCHAR(100),
    agent_id VARCHAR(120) NOT NULL,
    team VARCHAR(120) NOT NULL,
    model VARCHAR(120) NOT NULL,
    session_id VARCHAR(120),
    control_name VARCHAR(80) NOT NULL,
    action VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(80) NOT NULL,
    signature_id VARCHAR(120),
    policy_version BIGINT,
    tokens BIGINT NOT NULL,
    cost_usd NUMERIC(20,8) NOT NULL,
    gpu_seconds NUMERIC(20,6) NOT NULL,
    latency_ms DOUBLE PRECISION NOT NULL,
    message VARCHAR(2000) NOT NULL,
    context_json TEXT NOT NULL
);
CREATE INDEX audit_time ON audit_event(occurred_at);
CREATE INDEX audit_agent_time ON audit_event(agent_id, occurred_at);
CREATE INDEX audit_action_category ON audit_event(action, category);
CREATE TABLE signature (
    id VARCHAR(120) PRIMARY KEY,
    document TEXT NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL
);
