# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from semantic.v1 import semantic_pb2 as semantic_dot_v1_dot_semantic__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in semantic/v1/semantic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticServiceStub:
    """SemanticService runs AI-based checks. It only scores; the gateway decides
    block/redact/allow using thresholds from the policy file.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/noorpointer.semantic.v1.SemanticService/Analyze',
                request_serializer=semantic_dot_v1_dot_semantic__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=semantic_dot_v1_dot_semantic__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ScanArtifact = channel.unary_unary(
                '/noorpointer.semantic.v1.SemanticService/ScanArtifact',
                request_serializer=semantic_dot_v1_dot_semantic__pb2.ScanArtifactRequest.SerializeToString,
                response_deserializer=semantic_dot_v1_dot_semantic__pb2.ScanArtifactResponse.FromString,
                _registered_method=True)


class SemanticServiceServicer:
    """SemanticService runs AI-based checks. It only scores; the gateway decides
    block/redact/allow using thresholds from the policy file.
    """

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=semantic_dot_v1_dot_semantic__pb2.AnalyzeRequest.FromString,
                    response_serializer=semantic_dot_v1_dot_semantic__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ScanArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanArtifact,
                    request_deserializer=semantic_dot_v1_dot_semantic__pb2.ScanArtifactRequest.FromString,
                    response_serializer=semantic_dot_v1_dot_semantic__pb2.ScanArtifactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noorpointer.semantic.v1.SemanticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noorpointer.semantic.v1.SemanticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticService:
    """SemanticService runs AI-based checks. It only scores; the gateway decides
    block/redact/allow using thresholds from the policy file.
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noorpointer.semantic.v1.SemanticService/Analyze',
            semantic_dot_v1_dot_semantic__pb2.AnalyzeRequest.SerializeToString,
            semantic_dot_v1_dot_semantic__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noorpointer.semantic.v1.SemanticService/ScanArtifact',
            semantic_dot_v1_dot_semantic__pb2.ScanArtifactRequest.SerializeToString,
            semantic_dot_v1_dot_semantic__pb2.ScanArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
